server:
  port: 8070

spring:
  datasource:
    platform: oracle
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: student
    password: oracle123
  hikari:
    pool-name: Hikari Pool
    auto-commit: true
    connection-timeout: 10000
    connection-test-query: SELECT 1
    idle-timeout: 6000
    max-lifetime: 120000
    minimum-idle: 5
    maximum-pool-size: 10

  jpa:
   hibernate:
      ddl-auto: validate
   generate-ddl: true
   database-platform: org.hibernate.dialect.OracleDialect
   database:




